// ============================================================
// FIREBASE CONFIGURATION
// ============================================================
// WEEK 3: Replace the placeholder values below with YOUR
// Firebase project config from:
//   Firebase Console > Project Settings > Your Apps > Web App
//
// DO NOT edit this file until Week 3 (Deliverable 3).
// ============================================================

import { initializeApp } from "firebase/app";
import { getFirestore } from "firebase/firestore";

const firebaseConfig = {
  apiKey: "YOUR_API_KEY_HERE",
  authDomain: "YOUR_PROJECT.firebaseapp.com",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_PROJECT.appspot.com",
  messagingSenderId: "YOUR_SENDER_ID",
  appId: "YOUR_APP_ID",
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Firestore and export it
export const db = getFirestore(app);
